/* THIS DATA HAS BEEN TIDIED BY $npm run tidyCommondities */

export const COMMODITY_TYPES = [
  { type: 'main-dish', label: '🍱 餐盒', color: 'green', typeID: '1' },
  { type: 'à-la-carte', label: '🍖 單點', color: 'brown', typeID: '2' },
  { type: 'others', label: '🧃 飲料|水餃', color: 'indigo', typeID: '3' },
]

export const PRICE_VERSION = 2

export const COMMODITIES = [
  {
    type: COMMODITY_TYPES[0].type,
    label: COMMODITY_TYPES[0].label,
    color: COMMODITY_TYPES[0].color,
    items: [
      { name: '油淋雞腿飯', price: 140, priority: 1 },
      { name: '炸雞腿飯', price: 130, priority: 2 },
      { name: '滷雞腿飯', price: 130, priority: 3 },
      { name: '魚排飯', price: 110, priority: 4 },
      { name: '排骨飯', price: 115, priority: 5 },
      { name: '焢肉飯', price: 115, priority: 6 },
      { name: '蒜泥白肉飯', price: 115, priority: 7 },
      { name: '京醬肉絲飯', price: 110, priority: 8 },
      { name: '糖醋雞丁飯', price: 110, priority: 9 },
      { name: '雞肉絲飯', price: 100, priority: 10 },
      { name: '無骨雞排飯', price: 100, priority: 11 },
      { name: '蔬菜飯', price: 80, priority: 12 },
      { name: '大雞肉飯', price: 60, priority: 13 },
      { name: '小雞肉飯', price: 45, priority: 14 },
      { name: '雞胸肉沙拉', price: 160, priority: 15 },
      { name: '加蛋', price: 15, priority: 16, hideOnMode: 'both' },
      { name: '加菜', price: 15, priority: 17, hideOnMode: 'both' },
      // {
      //   name: '120',
      //   price: 120,
      //   menu: [
      //     { name: '炸雞腿飯', textIcon: '🍗', price: 120, priority: 0 },
      //     { name: '滷雞腿飯', textIcon: '🍗', price: 120, priority: 1 },
      //   ],
      //   showRelevancy: true,
      //   hideOnMode: 'commondity',
      //   priority: 0,
      // },
      // {
      //   name: '110',
      //   price: 110,
      //   menu: [
      //     { name: '蒜泥白肉飯', textIcon: '🥓', price: 110, priority: 0 },
      //     { name: '排骨飯', textIcon: '🥩', price: 110, priority: 1 },
      //     { name: '魚排飯', textIcon: '🐟', price: 110, priority: 2 },
      //     { name: '焢肉飯', textIcon: '🥩', price: 110, priority: 3 },
      //   ],
      //   showRelevancy: true,
      //   hideOnMode: 'commondity',
      //   priority: 1,
      // },
      // {
      //   name: '105',
      //   price: 105,
      //   menu: [
      //     { name: '京醬肉絲飯', textIcon: '🥓', price: 105, priority: 0 },
      //     { name: '糖醋雞丁飯', textIcon: '🐔', price: 105, priority: 1 },
      //   ],
      //   showRelevancy: true,
      //   hideOnMode: 'commondity',
      //   priority: 2,
      // },
      // {
      //   name: '95',
      //   price: 95,
      //   menu: [
      //     { name: '雞肉絲飯', textIcon: '🐔', price: 95, priority: 0 },
      //     { name: '無骨雞排飯', textIcon: '🥩 ', price: 95, priority: 1 },
      //   ],
      //   showRelevancy: true,
      //   hideOnMode: 'commondity',
      //   priority: 3,
      // },
    ],
  },
  {
    type: COMMODITY_TYPES[1].type,
    label: COMMODITY_TYPES[1].label,
    color: COMMODITY_TYPES[1].color,
    items: [
      { name: '油淋雞腿', price: 100, priority: 1 },
      {
        name: '炸雞腿',
        price: 90,
        priority: 2,
      },
      {
        name: '滷雞腿',
        price: 90,
        priority: 3,
      },
      { name: '魚排', price: 65, priority: 4 },
      { name: '排骨', price: 75, priority: 5 },
      { name: '焢肉', price: 75, priority: 6 },
      { name: '蒜泥白肉', price: 75, priority: 7 },
      { name: '京醬肉絲', price: 70, priority: 8 },
      { name: '糖醋雞丁', price: 70, priority: 9 },
      { name: '雞肉絲', price: 55, priority: 10 },
      { name: '無骨雞排', price: 55, priority: 11 },
      { name: '蔬菜', price: 30, priority: 12 },
      { name: '加蛋', price: 15, priority: 13 },
      { name: '加菜(大)', price: 30, priority: 14 },
      { name: '白飯', price: 10, priority: 15 },
      { name: '白飯(小)', price: 5, priority: 16 },
    ],
  },
  {
    type: COMMODITY_TYPES[2].type,
    label: COMMODITY_TYPES[2].label,
    color: COMMODITY_TYPES[2].color,
    items: [
      { name: '干貝水餃', price: 275, priority: 1 },
      { name: '招牌水餃', price: 240, priority: 2 },
      { name: '韭菜水餃', price: 240, priority: 3 },
      { name: '養生水餃', price: 275, priority: 4 },
      { name: '玉米水餃', price: 240, priority: 5 },
      { name: '果醋飲', price: 20, priority: 6 },
      { name: '果醋飲x3', price: 50, priority: 7 },
      { name: '原萃綠茶', price: 25, priority: 8 },
      { name: '樂天優格', price: 25, priority: 9 },
      { name: '蜂蜜牛奶', price: 23, priority: 10 },
      { name: '可樂Zero', price: 25, priority: 11 },
      { name: '維大力', price: 25, priority: 12 },
      { name: '樹頂蘋果汁', price: 40, priority: 13 },
      { name: '瓶裝水', price: 10, priority: 14 },
    ],
  },
]
